import type { Epic, UserStory } from './types';

const GITHUB_API_BASE = 'https://api.github.com';
const BATCH_SIZE = 5; // concurrent issue creation requests

export async function exportToGitHubIssues(
  owner: string,
  repo: string,
  epics: Epic[],
  token: string
): Promise<{ issues_created: number; issue_urls: string[] }> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
  };

  // Ensure labels exist (best-effort, won't fail if they exist already)
  await ensureLabels(owner, repo, headers);

  console.log(JSON.stringify({ event: 'export_start', owner, repo, epic_count: epics.length, ts: new Date().toISOString() }));

  // Flatten all stories with their parent epic
  const items = epics.flatMap(epic =>
    epic.stories.map(story => ({ epic, story }))
  );

  const issue_urls: string[] = [];

  // Process in parallel batches to avoid GitHub rate limits
  for (let i = 0; i < items.length; i += BATCH_SIZE) {
    const batch = items.slice(i, i + BATCH_SIZE);
    const results = await Promise.allSettled(
      batch.map(({ epic, story }) =>
        fetch(`${GITHUB_API_BASE}/repos/${owner}/${repo}/issues`, {
          method: 'POST',
          headers,
          body: JSON.stringify({
            title: `[${story.id}] ${story.title}`,
            body: buildIssueBody(epic, story),
            labels: buildLabels(story),
          }),
        }).then(async res => {
          if (!res.ok) {
            const err = await res.json().catch(() => ({}));
            throw new Error(
              `GitHub API error ${res.status}: ${(err as { message?: string }).message ?? res.statusText}`
            );
          }
          const issue = await res.json() as { html_url: string };
          return issue.html_url;
        })
      )
    );

    const failures: string[] = [];
    for (const result of results) {
      if (result.status === 'fulfilled') {
        issue_urls.push(result.value);
      } else {
        failures.push(result.reason instanceof Error ? result.reason.message : String(result.reason));
      }
    }
    // Only abort if the entire batch failed — partial success is acceptable
    if (failures.length > 0 && failures.length === batch.length) {
      throw new Error(`GitHub export batch failed: ${failures[0]}`);
    }
    if (failures.length > 0) {
      console.warn(JSON.stringify({ event: 'export_partial_failure', count: failures.length, reason: failures[0], ts: new Date().toISOString() }));
    }
  }

  console.log(JSON.stringify({ event: 'export_complete', owner, repo, issues_created: issue_urls.length, ts: new Date().toISOString() }));
  return { issues_created: issue_urls.length, issue_urls };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function buildIssueBody(epic: Epic, story: UserStory): string {
  const ac = story.acceptance_criteria
    .map(c => `- **GIVEN** ${c.given}, **WHEN** ${c.when}, **THEN** ${c.then}.`)
    .join('\n');

  return `## User Story

**Epic:** ${epic.name} (\`${epic.id}\`)

> As a **${story.actor}**, I want to **${story.action}**, so that **${story.outcome}**.

---

## Acceptance Criteria

${ac}

---

## Metadata

| Field | Value |
|---|---|
| **Priority** | ${story.priority} |
| **Effort** | ${story.effort} |
| **Phase** | ${story.phase} |
| **Value Score** | ${story.value_score.toFixed(2)} / 5.00 |
| **Business Value** | ${story.business_value}/5 |
| **User Impact** | ${story.user_impact}/5 |
| **Feasibility** | ${story.feasibility}/5 |

---

*Generated by [Idea → Agent](${process.env.NEXT_PUBLIC_BASE_URL})*`;
}

function buildLabels(story: UserStory): string[] {
  const labels: string[] = ['type: user-story'];

  const priorityLabel: Record<string, string> = {
    'Must Have': 'priority: critical',
    'Should Have': 'priority: high',
    'Could Have': 'priority: medium',
    "Won't Have": 'priority: low',
  };
  const phaseLabel: Record<string, string> = {
    MVP: 'phase: mvp',
    Stabilization: 'phase: stabilization',
    Enhancement: 'phase: enhancement',
    Growth: 'phase: growth',
  };

  if (priorityLabel[story.priority]) labels.push(priorityLabel[story.priority]);
  if (phaseLabel[story.phase]) labels.push(phaseLabel[story.phase]);

  return labels;
}

const LABELS_TO_CREATE = [
  { name: 'type: user-story', color: '0075ca', description: 'User story from Idea → Agent' },
  { name: 'priority: critical', color: 'd73a4a', description: 'Must Have' },
  { name: 'priority: high', color: 'e4e669', description: 'Should Have' },
  { name: 'priority: medium', color: '0e8a16', description: 'Could Have' },
  { name: 'priority: low', color: 'cfd3d7', description: "Won't Have" },
  { name: 'phase: mvp', color: 'f9d0c4', description: 'MVP phase' },
  { name: 'phase: stabilization', color: 'fef2c0', description: 'Stabilization phase' },
  { name: 'phase: enhancement', color: 'c2e0c6', description: 'Enhancement phase' },
  { name: 'phase: growth', color: 'bfd4f2', description: 'Growth phase' },
];

async function ensureLabels(
  owner: string,
  repo: string,
  headers: Record<string, string>
): Promise<void> {
  await Promise.allSettled(
    LABELS_TO_CREATE.map(label =>
      fetch(`${GITHUB_API_BASE}/repos/${owner}/${repo}/labels`, {
        method: 'POST',
        headers,
        body: JSON.stringify(label),
      })
    )
  );
}
