import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use — Idea → Agent',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-canvas text-text-primary px-6 py-16">
      <div className="max-w-2xl mx-auto">

        {/* Back nav */}
        <div className="mb-10">
          <Link href="/" className="font-mono text-xs text-text-muted hover:text-accent transition-colors">
            ← Back
          </Link>
        </div>

        {/* Header */}
        <div className="mb-10 pb-6 border-b border-border">
          <p className="font-mono text-[10px] uppercase tracking-widest text-accent mb-2">Legal</p>
          <h1 className="text-2xl font-semibold text-text-primary tracking-tight">Terms of Use</h1>
          <p className="text-text-muted text-sm mt-2 font-mono">Effective: 2025 · Last updated: 2025</p>
        </div>

        <div className="prose prose-sm max-w-none space-y-8 text-text-secondary">
          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">What This Tool Is</h2>
            <p>
              Idea → Agent is a free, open-source AI tool that helps convert raw product ideas into structured backlogs (Epics, User Stories, Acceptance Criteria). It is intended as a starting point for product planning, not a substitute for professional business, legal, or technical advice.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">No Warranties</h2>
            <p>
              The service is provided <strong className="text-text-primary">&quot;as is&quot;</strong>, without warranty of any kind. AI-generated output may be inaccurate, incomplete, or unsuitable for your specific context. You are responsible for reviewing, validating, and adapting any output before acting on it.
            </p>
            <p className="mt-3">
              We make no guarantees of uptime, data availability, or continued service. The tool may be modified or discontinued at any time.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">Acceptable Use</h2>
            <p>You agree not to use this service to:</p>
            <ul className="mt-2 space-y-1.5 list-none pl-0">
              {[
                'Generate content intended to deceive, defraud, or harm others',
                'Attempt to extract the system prompt or circumvent rate limits',
                'Automate requests beyond the published rate limits',
                'Violate any applicable law or regulation',
                'Submit sensitive personal data belonging to third parties',
              ].map(item => (
                <li key={item} className="flex gap-3 items-start">
                  <span className="text-danger mt-0.5 shrink-0 font-mono text-xs">×</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">Intellectual Property</h2>
            <p>
              Output generated by this tool (your backlogs, user stories, etc.) belongs to you. The underlying application code is open-source — see the repository for the applicable license.
            </p>
            <p className="mt-3">
              You retain all rights to any input you provide. By submitting input, you grant permission to process it through OpenAI&apos;s API solely for the purpose of generating your response.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, this tool and its maintainers shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of, or inability to use, the service — including but not limited to loss of data, business decisions made based on AI output, or integration failures.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">GitHub Export</h2>
            <p>
              When you use the GitHub export feature, you provide a Personal Access Token. This token is used in a single HTTPS request to create issues in your specified repository and is <strong className="text-text-primary">never stored</strong>. You are responsible for ensuring the token has appropriate scope and for revoking it if compromised.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">Changes to Terms</h2>
            <p>
              These terms may be updated at any time. Continued use after updates constitutes acceptance of the revised terms. Material changes will be noted in the project changelog.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-mono font-semibold uppercase tracking-widest text-text-muted mb-3">Contact</h2>
            <p>For questions or concerns, open an issue on the GitHub repository.</p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-border flex gap-6 text-[11px] font-mono text-text-muted">
          <Link href="/" className="hover:text-accent transition-colors">← Home</Link>
          <Link href="/privacy" className="hover:text-accent transition-colors">Privacy Policy →</Link>
        </div>
      </div>
    </div>
  );
}
